version: 2
jobs:
  build:
    working_directory: ~/BetterBlog
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: BetterBlog
      - image: circleci/postgres:9.6.9-alpine-postgis
        environment:
          POSTGRES_USER: BetterBlog
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: BetterBlog_test

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Wait for database
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the environment
      - run: cp .env.example .env
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Run tests
      - run:
          name: Run tests
          command: bundle exec rspec
      # Check code styling using Rubocop
      - run:
          name: Run code stylecheck
          command: bundle exec rubocop --fail-level warning
